version: "3"

services:
    pokitoki:
        container_name: pokitoki
        command: python3 -m bot.bot
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
          - ./config.yml:/code/config.yml:ro
          - bot_persistent_volume:/code/bot_data

volumes:
  bot_persistent_volume:
    name: bot_persistent_volume
